version: "3.8"

services:
  # PostgreSQL database service
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      - POSTGRES_USER=newuser
      - POSTGRES_PASSWORD=""
      - POSTGRES_DB=bookstore
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Spring Boot application service
  spring-app:
    build: .
    container_name: spring-app-container
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/bookstore
      - SPRING_DATASOURCE_USERNAME=newuser
      - SPRING_DATASOURCE_PASSWORD=""
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres-data: